
modal_dict = {
    "Colon": "Colonos",
    "Colonos": "Colonos",
    "Colonoscopy": "Colonos",
    "CT": "CT",
    "Dermos": "Dermos",
    "Dermoscopy": "Dermos",
    "Fundus": "Fundus",
    "Funduscopy": "Fundus",
    "MRI": "MRI",
    "US": "US",
    "xray": "Xray",
    "Xray": "Xray",
}

modal_map = {
    "Colonos": 0,
    "CT": 1,
    "Dermos": 2,
    "Fundus": 3,
    "MRI": 4,
    "US": 5,
    "Xray": 6,
}

modal_map_inv = {v: k for k, v in modal_map.items()}
modal_map_idx = {k: i for i, k in enumerate(modal_map_inv.keys())}

organ_level_1_dict = {
    "head&neck": ["BrainTumor", "BrainEnhancingTumor", "BrainNonEnhancingTumor", "BrainEdema", "Brainstroke", 
                  "Hippocampus", "opticcup", "opticdsc", "Tooth", "Lip", 
                  "CavityOral", "BuccalMucosa", "GlndThyroid", "Thyroidnodule", "ParotidL", 
                  "ParotidR", "GindSubmandL", "GindSubmandR"],
    "body": ["LeftLung", "RightLung", "LungCancer", "COVID", "GroundGlassesOpacities", 
             "Consolidation", "PleuraEffusion", "lungPneumothorax", "Bronchus", "Esophagus",
             "Heart", "LeftAtrium", "RightAtrium", "LeftVentricle", "RightVentricle",
             "LeftVentricularMyocardium", "MitralValve", "LeftVentricleEpicardium", "Leftatrialbloodchamber", "Rightatrialbloodchamber", 
             "Leftventricularbloodchamber", "Rightventricularbloodchamber", "Leftventricularmyocardium", "Rightventricularmyocardium", 
             "HeartLeftVentricleEpicardium", "HeartRightVentricleEpicardium", "BreastCancer", "Liver", "LiverCancer", 
             "GallBladder", "Pancreas", "PancreasCancer", "Spleen", "Kidney", "LeftKidney", 
             "RightKidney", "KidneyTumor", "Adrenal", "LeftAdrenalGland", "RightAdrenalGland", 
             "Stomach", "Duodenum", "Colon", "ColonCancer", "Rectum", 
             "polyp", "Instrument", "Bladder", "Prostate", "ProstateTumor"],
    "bone": ["Mandible", "LeftCollarBone", "RightCollarBone", "CervicalSpine", "LumbarSpine", 
             "ThoracicSpine", "FemurBone", "FemurCartilage", "TibiaBone", "TibiaCartilage"],
    "vessel": ["CarotidArteryLeft", "CarotidArteryRight", "PulmonaryArtery", "Aorta", "InferiorVenaCava", 
               "Postcava"],
    "skin": ["Skin"],
}

organ_level_1_map = {
    "head&neck": 0,
    "body": 1,
    "bone": 2,
    "vessel": 3,
    "skin": 4,
}

organ_level_1_map_inv = {v: k for k, v in organ_level_1_map.items()}
organ_level_1_map_idx = {k: i for i, k in enumerate(organ_level_1_map_inv.keys())}

organ_level_2_dict = {
    "cranium&brain": ["BrainTumor", "BrainEnhancingTumor", "BrainNonEnhancingTumor", "BrainEdema", "Brainstroke", "Hippocampus"],
    "face": ["opticcup", "opticdsc", "Tooth", "Lip", "CavityOral", "BuccalMucosa"],
    "neck": ["GlndThyroid", "Thyroidnodule", "ParotidL", "ParotidR", "GindSubmandL", "GindSubmandR"],
    "chest": ["LeftLung", "RightLung", "LungCancer", "COVID", "GroundGlassesOpacities", 
              "Consolidation", "PleuraEffusion", "lungPneumothorax", "Bronchus", "Esophagus",
              "Heart", "LeftAtrium", "RightAtrium", "LeftVentricle", "RightVentricle",
              "LeftVentricularMyocardium", "MitralValve", "LeftVentricleEpicardium", "Leftatrialbloodchamber", "Rightatrialbloodchamber", 
              "Leftventricularbloodchamber", "Rightventricularbloodchamber", "Leftventricularmyocardium", "Rightventricularmyocardium", 
              "HeartLeftVentricleEpicardium", "HeartRightVentricleEpicardium", "BreastCancer"],
    "abdomen": ["Liver", "LiverCancer", "GallBladder", "Pancreas", "PancreasCancer",
                "Spleen", "Kidney", "LeftKidney", "RightKidney", "KidneyTumor", 
                "Adrenal", "LeftAdrenalGland", "RightAdrenalGland", "Stomach", "Duodenum", 
                "Colon", "ColonCancer", "Rectum", "polyp", "Instrument"],
    "pelvis": ["Bladder", "Prostate", "ProstateTumor"],
    "cranium&face": ["Mandible"],
    "trunk": ["LeftCollarBone", "RightCollarBone", "CervicalSpine", "LumbarSpine", "ThoracicSpine"],
    # "upperlimb": [],
    "lowerlimb": ["FemurBone", "FemurCartilage", "TibiaBone", "TibiaCartilage"],
    "artery": ["CarotidArteryLeft", "CarotidArteryRight", "PulmonaryArtery", "Aorta"],
    "vein": ["InferiorVenaCava", "Postcava"],
    "skin": ["Skin"],
}

organ_level_2_map = {
    "cranium&brain": 0,
    "face": 1,
    "neck": 2,
    "chest": 3,
    "abdomen": 4,
    "pelvis": 5,
    "cranium&face": 6,
    "trunk": 7,
    # "upperlimb": 8,
    "lowerlimb": 9,
    "artery": 10,
    "vein": 11,
    "skin": 12,
}

organ_level_2_map_inv = {v: k for k, v in organ_level_2_map.items()}
organ_level_2_map_idx = {k: i for i, k in enumerate(organ_level_2_map_inv.keys())}

organ_level_3_dict = {
    "brain": ["BrainTumor", "BrainEnhancingTumor", "BrainNonEnhancingTumor", "BrainEdema", "Brainstroke"],
    "hippocampus": ["Hippocampus"],
    # "pituitary": [],
    "eye": ["opticcup", "opticdsc"],
    # "ear": [],
    # "nose": [],
    "mouth": ["Tooth", "Lip", "CavityOral", "BuccalMucosa"],
    # "tongue": [],
    "thyroid": ["GlndThyroid", "Thyroidnodule"],
    "parotid": ["ParotidL", "ParotidR"],
    "saliarygland": ["GindSubmandL", "GindSubmandR"],
    "lung": ["LeftLung", "RightLung", "LungCancer", "COVID", "GroundGlassesOpacities", 
             "Consolidation", "PleuraEffusion", "lungPneumothorax"],
    "trachea": ["Bronchus"],
    "esophagus": ["Esophagus"],
    "heart": ["Heart", "LeftAtrium", "RightAtrium", "LeftVentricle", "RightVentricle",
              "LeftVentricularMyocardium", "MitralValve", "LeftVentricleEpicardium", 
              "Leftatrialbloodchamber", "Rightatrialbloodchamber", 
              "Leftventricularbloodchamber", "Rightventricularbloodchamber", 
              "Leftventricularmyocardium", "Rightventricularmyocardium", 
              "HeartLeftVentricleEpicardium", "HeartRightVentricleEpicardium"],
    "breast": ["BreastCancer"],
    "liver": ["Liver", "LiverCancer"],
    "gallbladder": ["GallBladder"],
    "pancreas": ["Pancreas", "PancreasCancer"],
    "spleen": ["Spleen"],
    "kidney": ["Kidney", "LeftKidney", "RightKidney", "KidneyTumor"],
    "adrenal": ["Adrenal", "LeftAdrenalGland", "RightAdrenalGland"],
    "stomach": ["Stomach"],
    "intestine": ["Duodenum", "Colon", "ColonCancer", "Rectum", "polyp", "Instrument"],
    "bladder": ["Bladder"],
    # "uterus": [],
    # "ovary": [],
    "prostate": ["Prostate", "ProstateTumor"],
    # "seminalvesicle": [],
    # "skull": [],
    # "maxilla": [],
    "mandible": ["Mandible"],
    "collarbone": ["LeftCollarBone", "RightCollarBone"],
    # "rib": [],
    # "pelvis": [],
    "spine": ["CervicalSpine", "LumbarSpine", "ThoracicSpine"],
    # "shoulder": [],
    # "humerus": [],
    # "elbow": [],
    # "ulna": [],
    # "radius": [],
    # "wrist": [],
    # "hand": [],
    # "hip": [],
    "femur": ["FemurBone", "FemurCartilage"],
    # "knee": [],
    "tibia": ["TibiaBone", "TibiaCartilage"],
    # "fibula": [],
    # "ankle": [],
    # "foot": [],
    # "intracranialartery": [],
    "carotidarery": ["CarotidArteryLeft", "CarotidArteryRight"],
    "pulmonaryartery": ["PulmonaryArtery"],
    "aorta": ["Aorta"],
    # "limbartery": [],
    # "cranialvein": [],
    # "jugularvein": [],
    # "pulmonaryvein": [],
    # "precava": [],
    "postcava": ["InferiorVenaCava", "Postcava"],
    # "limbvein": [],
    "skin": ["Skin"],
}

organ_level_3_map = {
    "brain": 0,
    "hippocampus": 1,
    # "pituitary": 2,
    "eye": 3,
    # "ear": 4,
    # "nose": 5,
    "mouth": 6,
    # "tongue": 7,
    "thyroid": 8,
    "parotid": 9,
    "saliarygland": 10,
    "lung": 11,
    "trachea": 12,
    "esophagus": 13,
    "heart": 14,
    "breast": 15,
    "liver": 16,
    "gallbladder": 17,
    "pancreas": 18,
    "spleen": 19,
    "kidney": 20,
    "adrenal": 21,
    "stomach": 22,
    "intestine": 23,
    "bladder": 24,
    # "uterus": 25,
    # "ovary": 26,
    "prostate": 27,
    # "seminalvesicle": 28,
    # "skull": 29,
    # "maxilla": 30,
    "mandible": 31,
    "collarbone": 32,
    # "rib": 33,
    # "pelvis": 34,
    "spine": 35,
    # "shoulder": 36,
    # "humerus": 37,
    # "elbow": 38,
    # "ulna": 39,
    # "radius": 40,
    # "wrist": 41,
    # "hand": 42,
    # "hip": 43,
    "femur": 44,
    # "knee": 45,
    "tibia": 46,
    # "fibula": 47,
    # "ankle": 48,
    # "foot": 49,
    # "intracranialartery": 50,
    "carotidarery": 51,
    "pulmonaryartery": 52,
    "aorta": 53,
    # "limbartery": 54,
    # "cranialvein": 55,
    # "jugularvein": 56,
    # "pulmonaryvein": 57,
    # "precava": 58,
    "postcava": 59,
    # "limbvein": 60,
    "skin": 61,
}

organ_level_3_map_inv = {v: k for k, v in organ_level_3_map.items()}
organ_level_3_map_idx = {k: i for i, k in enumerate(organ_level_3_map_inv.keys())}

organ_list = [
    "BrainTumor", "BrainEnhancingTumor", "BrainNonEnhancingTumor", "BrainEdema", "Brainstroke", 
    "Hippocampus", "opticcup", "opticdsc", "Tooth", "Lip", 
    "CavityOral", "BuccalMucosa", "GlndThyroid", "Thyroidnodule", "ParotidL", 
    "ParotidR", "GindSubmandL", "GindSubmandR", "LeftLung", "RightLung", 
    "LungCancer", "COVID", "GroundGlassesOpacities", "Consolidation", "PleuraEffusion", 
    "lungPneumothorax", "Bronchus", "Esophagus", "Heart", "LeftAtrium", 
    "RightAtrium", "LeftVentricle", "RightVentricle", "LeftVentricularMyocardium", "MitralValve", 
    "LeftVentricleEpicardium", "Leftatrialbloodchamber", "Rightatrialbloodchamber", 
    "Leftventricularbloodchamber", "Rightventricularbloodchamber", "Leftventricularmyocardium", 
    "Rightventricularmyocardium", "HeartLeftVentricleEpicardium", "HeartRightVentricleEpicardium", 
    "BreastCancer", "Liver", "LiverCancer", "GallBladder", "Pancreas", 
    "PancreasCancer", "Spleen", "Kidney", "LeftKidney", "RightKidney", 
    "KidneyTumor", "Adrenal", "LeftAdrenalGland", "RightAdrenalGland", "Stomach", 
    "Duodenum", "Colon", "ColonCancer", "Rectum", "polyp", 
    "Instrument", "Bladder", "Prostate", "ProstateTumor", "Mandible", 
    "LeftCollarBone", "RightCollarBone", "CervicalSpine", "LumbarSpine", "ThoracicSpine", 
    "FemurBone", "FemurCartilage", "TibiaBone", "TibiaCartilage", "CarotidArteryLeft", 
    "CarotidArteryRight", "PulmonaryArtery", "Aorta", "InferiorVenaCava", "Postcava", "Skin"
]
organ_idx = {k: i for i, k in enumerate(organ_list)}
